source/github/events/pull_request.ts

Even though a valid action was triggered (opening a PR for example), peril kept printing
```Don't know this action``` 
which was confusing

add missing break in case switch

---

source/db/mongo.ts

Mentioned in #11
The `integrationDB` const was always undefined, I took a look at the mongojs doc and did the changes necessary and now it seems to be working as expected

Fix mongo config

---

source/danger/danger_runner.ts

I use to get the following error:
```
Type Error Executor is not a function
```
I guess the import was just wrong

fix executor import in runner danger

---

.gitignore
package.json
source/api/fetch.ts
source/api/github.ts
source/danger/_tests/_danger_runner.test.ts
source/danger/_tests/fixtures/dangerfile_insecure.ts
source/danger/danger_run.ts
source/danger/danger_runner.ts
source/db/_tests/__snapshots__/_json.test.ts.snap
source/db/_tests/_json.test.ts
source/db/index.ts
source/db/json.ts
source/db/postgres.ts
source/github/events/_tests/_github_runner-setup.test.ts
source/github/events/create_installation.ts
source/github/events/github_runner.ts
source/github/lib/github_helpers.ts
source/globals.ts
source/peril.ts
source/routing/_tests/_router.test.ts
source/routing/router.ts
yarn.lock

This means your _peril_ config can be in a JSON file in a repo, so it can easily be diffed, collaborated on etc. Probably a really good pattern for controlling your rules for repos overall too IMO.

Also support JSON-based settings instead of postgres

---

source/github/events/_tests/_github_runner-prs.test.ts
source/github/events/github_runner.ts
source/github/lib/github_helpers.ts

Adds the final safety net around running Danger on an open source org. Making sure that changes from non-admins are not allowed to run code with escalated permissions.
Fixes #95

Add org checks for changing  Dangerfiles on a PR

---

package.json
source/peril.ts
yarn.lock

I am aiming to get familiar with this codebase and hope to contribute small things (adding types, fixing typos, etc.) as I navigate through the codebase and try to understand what's going on.
I was working on a small Express-based project of my own and learned that there are types for the body-parser package, and that was one of the first things I saw in `peril.ts`. 😄

refactor(types): add body-parser types

---

source/danger/danger_run.ts
source/github/events/_tests/_github_runner-events.test.ts
source/github/events/_tests/_github_runner-runs.test.ts
source/github/events/_tests/_github_runner-setup.test.ts
source/github/events/github_runner.ts
source/github/lib/github_helpers.ts
source/routing/router.ts

Fixes #100
This just hit me also, which means I'm in a good place to test it. I feel like this was really an issue with two bits of data coming into the functions which made it confusing which to use. Now the settings is more constrained.
Plus I strengthened the typings in the github runner and it caught a few things 👍

Allow any repo to run without having to declare it in the settings

---

.gitignore
package.json
source/api/_tests/fixtureAPI.ts
source/danger/_tests/_danger_runner.test.ts
source/danger/_tests/_peril_platform.test.ts
source/danger/_tests/fixtures/dangerfile_import_module.ts
source/danger/danger_runner.ts
tsconfig.json
yarn.lock

The key here, I think, is that the recursive look back for node_modules doesn't find anything as danger files used to be evaluated inside `/tmp/`.

Allow node_module resolution for dangerfiles run by peril

---

package.json
source/danger/_tests/_danger_runner.test.ts
source/danger/danger_runner.ts
yarn.lock

#114 failed because of heroku's read-only FS, very reasonable. I was taking a guess. This moves it to work entirely in-memory.

Update to danger's 2a5 which allows in-memory dangerfiles

---

.vscode/launch.json
package.json
source/index.ts
source/peril.ts

Adding [node cluster](https://nodejs.org/api/cluster.html) support to allow server to:
- Recover automatically from crashes 
- Improve resource usage when multi-core servers are used
I think this will be particularly useful for github organizations with a lot of repositories running either on heroku professional dynos or any other mulit-core machine.

Feature - Adding node cluster support

---

docs/setup_for_org.md

I expanded a bit the docs on how do get the bot id for those not that familiar with Github API.
I also managed to get it via the GraphQL API, but was not sure how it would fit the docs. I will leave the query here just in case anyone figures it out in the future how to not be so verbose
```graphql
query BotIdForIssueOrPullRequest($url: URI!) {
resource(url: $url) {
__typename
...pr
...issue
}
}
fragment issue on Issue {
comments(first: 100) {
nodes {
author {
...author
}
}
}
}
fragment pr on PullRequest {
comments(first: 10) {
nodes {
author {
...author
}
}
}
}
fragment author on Bot {
login
databaseId
}
```
and the data would be just the PR or Issue URL, no id handling needed
```json
{
"url": "https://api.github.com/repos/[org]/[repo]/issues/[pr_or_issue_id]"
}
```

Adding more details to PERIL_BOT_USER_ID docs

---

CHANGELOG.md
README.md
source/danger/_tests/_danger_runner.test.ts
source/danger/_tests/_danger_runner_paths.test.ts
source/danger/danger_runner.ts
source/db/index.ts
source/github/events/_tests/_github_runner-events.test.ts
source/github/events/_tests/_github_runner-prs.test.ts
source/github/events/_tests/_github_runner-runs.test.ts
source/github/events/_tests/_github_runner-setup.test.ts
source/github/events/github_runner.ts

Added the ability to expose an ENV var via the `peril` object in the runtime, I wanted to use the Slack API in one of our Artsy Dangerfiles, but there wasn't a way to actually pass the secret to the Dangerfile. 
This also brings back the CHANGELOG, I don't think there's "versions" but I do tend to work in batches. So I won't force others to do it, but I'll leave myself notes in there.

Adds support for passing through specific ENV Vars

---

package.json
yarn.lock

We're getting errors running Danger on our fresh install of Peril:
----
It's erroring out on `babel.loadOptions`, which is a new function added in babel 7.
The root cause seems to be while upgrading Peril to the new version (https://github.com/danger/peril/commit/8ef430215895c92028d543c2539d4a74f1877c46) of Danger, the version of babel was not upgraded to match it.
----
This PR upgrades to babel 7, same as Danger's: https://github.com/danger/danger-js/commit/f9ab02b21714954563ff63d6320378ec0bb464a1

Error running Danger

---

package.json
yarn.lock

Saw this in the logs:
```
Request failed [404]: https://github.com/timehop/apicard/pull/932.diff
Response: Not Found
```
Poked around and saw this commit for alpha 13: https://github.com/danger/danger-js/commit/51e0bf838970b1c3d0e8e5515680abf759f1fc53

Danger: Update to alpha 13

---

source/github/events/github_runner.ts
source/github/events/types/pull_request_opened.types.ts

i noticed that peril was crashing on some test prs i was opening that
were just one-liners with only a title. in that case, the `pr.body` is
`null` and not `""`
i only see this one reference to `pr.body`, although a safer thing might be to cast the `body` to a string when ingesting the webhook data. thoughts?

pr.body type definition now nullable

---

package.json
source/danger/_tests/_danger_run.test.ts
source/danger/danger_run.ts
source/danger/danger_runner.ts
source/db/_tests/__snapshots__/_json.test.ts.snap
source/db/index.ts
source/db/json.ts
source/db/postgres.ts
source/github/events/_tests/_github_runner-runs.test.ts
source/github/events/_tests/_github_runner-validations.test.ts
source/github/events/create_installation.ts
source/peril.ts
source/scheduler/_tests/_runJob.test.ts
source/scheduler/_tests/_startScheduler.test.ts
source/scheduler/runJob.ts
source/scheduler/startScheduler.ts
source/testing/installationFactory.ts
yarn.lock

This is a simple in-memory scheduler for now, if/when something more complex is needed than it can be built out in the same way we handle JSON vs Postgres for an installation setting.

Support for a scheduler

---

source/api/pr/dsl.ts
source/db/json.ts
source/globals.ts

This allows us to re-use the same logic for the installation ID parsing in both the DSL and the JSON DB.
This is a small change that I plan to use in follow up work.

Factor out getInstallationId

---

source/db/_tests/__snapshots__/_json.test.ts.snap
source/db/_tests/_json.test.ts
source/db/json.ts
source/github/lib/github_helpers.ts

This extracts a util that is able to get a file from GitHub with just the Peril environment setup (no need to manually do a token dance).
It is intended that this util will be used in post install setup scripts in danger plugins, so ease of use is important.

Extract GitHub file access utility

---

source/danger/_tests/_danger_run.test.ts
source/danger/danger_run.ts
source/github/events/_tests/_github_runner-events.test.ts
source/github/events/_tests/_github_runner-prs.test.ts
source/github/events/github_runner.ts

https://github.com/artsy/artsy-danger/pull/34 added a specific RFC which wanted to only run on closed PRs, but it looks like Peril didn't support that. So #167 and this PR. I could probably use this as a reasonable to break out our PR dangerfile into many also.

Support doing multiple runs from the same event

---

docs/staging.md
package.json
source/api/pr/dsl.ts
source/danger/_tests/_danger_run.test.ts
source/danger/_tests/_danger_runner.test.ts
source/danger/_tests/_danger_runner_paths.test.ts
source/danger/_tests/_danger_runner_peril.test.ts
source/danger/append_peril.ts
source/danger/danger_run.ts
source/danger/danger_runner.ts
source/danger/peril_platform.ts
source/github/events/_tests/_github_runner-events.test.ts
source/github/events/_tests/_github_runner-runs.test.ts
source/github/events/createPRDSL.ts
source/github/events/create_installation.ts
source/github/events/github_runner.ts
source/github/lib/github_helpers.ts
source/globals.ts
source/runner/hyper-api.ts
source/runner/index.ts
source/scheduler/_tests/_runJob.test.ts
source/scheduler/runJob.ts
source/tasks/runTask.ts
source/tasks/startTaskScheduler.ts
tsconfig.json
yarn.lock

Re: https://github.com/danger/peril/issues/159 https://github.com/danger/danger/issues/42
Deprecates: #183  
This sets up Peril to be able to run a Dangerfile inside a [hyper](https://hyper.sh) [function](https://docs.hyper.sh/Feature/container/func.html) instead of executing in the same server/process. Allowing safe, scalable execution of unsafe code. 
* GH sends webhook to Peril
* Webhook is routed internally and could trigger some dangerfile runs
* Inside Peril the Danger DSL is set up and then executed via [vm2](https://github.com/patriksimek/vm2)
This is fine for trusted code, but it's not doable when dealing with code you really want to not screw up your machine. This has lead me down many paths 👍
AWS Lamda was a great first start, but it turned out to have an issue in that the …

Create a peril danger-JS runner with hyper functions

---

.travis.yml
source/github/lib/github_helpers.ts

Looks like an update to the fetch dependency broke this in prod but not in tests.

Remove the body param from api requests if it's a GET/HEAD

---

package.json
yarn.lock

Eh, looks like node fetch 2.1.x just isn't quite fully baked yet

Use node-fetch 2.0

---

source/github/events/github_runner.ts

This fixes the "Cannot find dangerfile" error from #223, but the "regeneratorRuntime is not defined" error persists.

Fix Dangerfile on branch

---

.gitignore
.travis.yml
docs/env/staging.md
now.staging.json
package.json
source/globals.ts
yarn.lock

Came to the conclusion that I was gonna go with now for peril. This PR makes that possible.
* Handle a weird case around https://github.com/zeit/now-cli/issues/749 with pub/private keys
* Updates staging docs
* Moves as much as possible to the `next.staging.json`
* Should be deploying automatically on master merges

Support running on Zeit's Now

---

source/api/auth/github.ts
source/db/__mocks__/getDB.ts
source/routing/_tests/_router.test.ts
source/routing/_tests/create-mock-response.ts
source/runner/triggerSandboxRun.ts
yarn.lock

I wanted to make it easier to test the db and requests, and most of the time to pull that off you have to use a bunch of `as any`s which isn't great IMO. 
This uses TypeScript's interface merging to let tests treat an object as both the original object, and a mocked version of it, so you're fine to do `x.y`, use x when it's expected `thing(x)` and also fine to do `x.mockImplementationOnce`.

Improve the types used in common testing scenarios

---

source/github/events/github_runner.ts

closes #204 
Playing around with learning typescript this weekend and thought I would do some hacking on open peril issues.
This fixes the crash by adding a defensive return and logging the error. A potential future improvement would be doing some earlier validation and selection of events, but I'm not :100: on the javascript conventions around this (and a similar pattern is already used in the run*run fns).

Fix crash when a non-repo event is passed to runPRRun

---

CHANGELOG.md
package.json
source/api/_tests/fixtureAPI.ts
source/api/api.ts
source/api/graphql/index.ts
source/api/pr/dsl.ts
source/danger/_tests/_danger_runner.test.ts
source/db/_tests/_json.test.ts
source/db/getDB.ts
source/db/json.ts
source/db/mongo.ts
source/github/events/github_runner.ts
source/index.ts
source/peril.ts
source/plugins/recordWebhooks.ts
source/plugins/utils/recordWebhookWithRequest.ts
source/routing/router.ts
source/scripts/setup-plugins.ts
tslint.json

This allows you to send a mutation requesting 5m of webhooks to be recorded, these are stored in the db and are wiped every time you request a new one.
Also starts to remove all default exports.

Initial implementation for recording all webhooks for 5m

---

docs/setup_for_org.md

This PR adds Peril settings repos for @Moya and @RxSwiftCommunity. I can add https://github.com/ashfurrow/peril-settings too, but it's a personal server instead of an organization one, and it might raise more questions than it answers. Up to you!

Adds Moya and RxSwiftCommunity repos.

---

CHANGELOG.md
docs/setup_for_org.md

Since #278 (and https://github.com/danger/danger-js/pull/594), Danger has used the Checks API, which needs permissions from GitHub. This PR updates the docs and makes a note in the Changelog. See discussion in #328.

Adds docs for Checks API permissions.

---

source/danger/peril_platform.ts

via setting `SKIP_CHECKS_SUPPORT` to true in the env.
I got no tests, but I'm like 90% sure this is fine.

Adds an option to skip the checks API when using peril 

---

source/plugins/installationLifeCycle.ts
source/routing/router.ts

With the intention being to block the runtime from having access to installation webhooks
re: #362

Reshuffles the routing around in Peril

---

source/danger/danger_runner.ts

Danger requires filenames to be different for each script as it uses a comparison based algorithm to identify the index of the script to run.
https://github.com/danger/danger-js/blob/99705705e3715b4c43fb4e82c9b8783c40d0d522/source/runner/runners/inline.ts#L87-L89
The code would use the same random name for all files, effectively running only the 1st one multiple times.
generate a random string for each step of the iteration

Ensure a proper random name is generated for each source

---

source/github/events/github_runner.ts

As discussed in #388 this PR opens up all events hooks so peril can be used as a general purpose danger engine.

Allow all events to run

---

package.json
source/danger/append_peril.ts
source/danger/peril_platform.ts
source/github/events/create_installation.ts
source/github/events/github_runner.ts
source/plugins/utils/recordWebhookWithRequest.ts
source/routing/router.ts
tsconfig.json
yarn.lock

- Fixes mongooses a type issues with mongo prevent proper upgrade
- Prepares for next version of danger ~(broken ATM pending https://github.com/danger/danger-js/pull/696)~

Bumps dependencies and make it ready for latest danger-js

---

source/tasks/startTaskScheduler.ts

I'm not 100% sure about this bug fix, but we've been seeing this problem at Artsy where RFC tasks get run multiple times where configured in an array:
https://github.com/artsy/peril-settings/blob/36ccb57d6aea1ffd88fbb93cce8f9429fcc75724/peril.settings.json#L43
It looks like it just runs the first task over and again for each element in that array. I _think_ this PR fixes that, but I didn't see a test to be sure.

Fixes multiple task repition bug

---

.circleci/config.yml

This moves peril over to using circleci 2.1. 
I've done a few things here:
- added an [executor](https://circleci.com/docs/2.0/configuration-reference/#executors-requires-version-21) which encapsulates the common node runtime and working directory logic
- added a [command](https://circleci.com/docs/2.0/configuration-reference/#commands-requires-version-21) to remove duplication of caching/installing packages
- added a deploy job
- cleaned up the workflow to work well with a deploy step

Clean up circle config, add deploy step

---

.circleci/config.yml

This install step works with the individual apps, but doesn't work with deploy. It's not really needed because this isn't a yarn workspace. I just removed it for now.

Remove broken caching step from deploy

---

api/source/db/_tests/__snapshots__/_json.test.ts.snap
api/source/db/json.ts

This is a small change to fix https://github.com/danger/peril/issues/421.
Prior to this change, the `disable_github_check` was not having any effect.

Fix 'disable_github_check' setting

---

app.json
docs/setup_for_org.md

Fixes https://github.com/danger/peril/issues/419
This reintroduces support for running the Peril API on Heroku since it has been moved to a mono repo.
Here is the Heroku deploy button pointing at my branch. You should be able to deploy a peril API instance just like before.
[![Deploy](https://www.herokucdn.com/deploy/button.png)](https://heroku.com/deploy?template=https://github.com/jtreanor/peril/tree/heroku-monorepo)
To update an existing peril Heroku app to use the mono repo, you can follow these steps:
1. Add the build pack: `heroku buildpacks:add -a <app> https://github.com/lstoll/heroku-buildpack-monorepo -i 1`.
2. Add the config variable: `heroku config:set APP_BASE=api`.
3. Trigger a new deploy. Check out latest and run `git push heroku master`.

Add support for running api on Heroku with mono repo

---

docs/settings_repo_info.md

1. I started reading [docs/settings_repo_info.md](https://github.com/danger/peril/blob/master/docs/settings_repo_info.md) and found some broken links. This PR updates the links I found to be broken.
2. I saw that `availablePerilRuntimeDependencies` section [was removed on this PR](https://github.com/danger/peril/commit/26911cd5e55cac9009d3a5bc5e5afa21cbf1665f#diff-b6a345fc4af56c0c9121295b9e84c280) so I removed a sentence mentioning it

Update broken links docs/settings_repo_info.md

---

Dockerfile

Should be copying files to `/app` instead of `/app/api`

Fix Dockerfile copy destination path

---

api/source/github/events/utils/commenting.ts

This fixes https://github.com/danger/peril/issues/436.
By not passing anything to the now option `git` parameter of `handleResults`, posting comments now works without crashing. See https://github.com/danger/danger-js/pull/887 for the Danger changes.
Thanks to @orta for the quick update to Danger in 1e1b12268a543efedc898d83c73ba5e418b777c7.

Don't pass GitDSL to handleResults

---

api/source/github/events/_tests/_github_runner-prs.test.ts
api/source/github/events/createPRDSL.ts
api/source/github/events/handlers/_tests/__snapshots__/_pr-create-fixture.test.ts.snap
api/source/github/events/handlers/_tests/_pr-create-fixture.test.ts
api/source/github/events/handlers/_tests/fixtures/PerilRunnerPRBootStrapExample.json
api/source/github/events/handlers/pr.ts

This fixes https://github.com/danger/peril/issues/367.
Currently, the full DSL is not used for non-sandboxed PR runs. This fixes that by calling the existing `createPRDSL` function and providing the GH access token so the API can be authenticated.
This was not a problem for sandboxed runs since `guthub.api` and `github.utils` are recreated in `appendPerilContextToDSL`.

Use full DSL for non-sandboxed PR runs

---

api/source/github/events/handlers/_tests/_pr-create-fixture.test.ts
api/source/github/events/handlers/pr.ts

Fixes #441.
Not sure why a PR would ever come back 404 from GitHub (since GitHub gives Peril the PR number, and they can't be easily deleted), but anyway. [The method ultimately can throw](https://github.com/danger/danger-js/blob/838afd74efdbbbe99dd86cd1757c595423031eb2/source/platforms/GitHub.ts#L47-L51) and this seemed like the best spot to put error-handling.

Catches error from missing PR

---

api/source/api/pr/dsl.ts
api/source/routing/router.ts

closes #444 
I noticed a lot of warnings from winston about an invalid log level. Looks like there were just some places where `winston.log` was being called with `router` being the first argument which was being treated as a log level.

Fix winston warnings around missing log level

---

api/package.json
api/source/github/events/_tests/_github_runner-prs.test.ts
api/source/github/events/handlers/_tests/_pr-create-fixture.test.ts
api/source/github/events/handlers/pr.ts
api/source/github/lib/github_helpers.ts
api/yarn.lock

Weirdly GitHub's been sending the same PR web hook to peril for the last 2 weeks, with a PR which doesn't exist. This took down Peril, hah!
https://github.com/danger/peril/pull/442 took a stab a this by catching errors from the Danger run, but TBH - Peril shouldn't be running danger at all if a PR doesn't exist. This PR adds a validation that indeed, the PR exists before running.
And updates sentry, because the logs were useless.

Updates sentry and proves a PR 

---

dashboard/src/components/installation/Settings.tsx

Whenever we updated the JSON settings URL, we noticed that the Slack Incoming Webhook URL was getting overwritten with the same value (ie: both values were being saved as the JSON URL). This should fix that.
Didn't see any tests to update, but let us know 👍
Looks like Prettier updated the file with some unrelated style changes.

Fixes problem where JSON url was overwriting Slack webhook url

---

hooks/pre_build

At the moment autobuilds from docker are failing as below.
```
Executing pre_build hook...
Could not execute hook at 'hooks/pre_build'. Is it missing a #! line?
```
As per dockers [docs](https://docs.docker.com/docker-hub/builds/advanced/) this PR adds the `#!/bin/bash` prefix to the file.

Prefix pre_hook bash file with #!/bin/bash

---

api/source/logger.ts

I was hitting an error when trying to deploy a Peril update for @RxSwiftCommunity:
```
remote:        $ node out/scripts/setup-plugins.js
remote:        /tmp/build_f6f92644/node_modules/winston-transport/legacy.js:18
remote:            throw new Error('Invalid transport, must be an object with a log method.');
remote:            ^
remote:
remote:        Error: Invalid transport, must be an object with a log method.
remote:            at new LegacyTransportStream (/tmp/build_f6f92644/node_modules/winston-transport/legacy.js:18:11)
remote:            at DerivedLogger.add (/tmp/build_f6f92644/node_modules/winston/lib/winston/logger.js:345:11)
remote:            at Object.winston.(anonymous function).args [as add] (/tmp/build_f6f92644/node_modules/winston/lib/winston.js:110:68)
remote: …
```

Updates Papertrail invocation

---

api/source/danger/append_peril.ts
api/source/danger/danger_runner.ts

This tries to fix the logic around appending "Peril context"  before executing inline runner. Current logic checks for `sandbox` property but this is never set, so appending peril context is never executed.
From user perspective - this should fix accessing environment variables via `peril.env.*`, which is currently not working (`peril` objects is just `{}`, it doesn't even have `.env` field)
Closes https://github.com/danger/peril/issues/474

fix passing peril instance to inline runner

---

api/package.json
api/yarn.lock

Security vulnerabilities detected by dependabot:
- Bump babel-plugin-syntax-async-functions from 7.0.0-alpha.19 to 7.0.0-beta.0
- Bump babel-plugin-transform-regenerator from 7.0.0-alpha.19 to 7.0.0-beta.3
- Bump tslint from 5.14.0 to 6.1.3
- Bump types/debug from 0.0.30 to 4.1.5
- Bump typescript from 3.4.1 to 4.3.2
Tested with some basic rules like "merge on green" and "auto-approve and merge on release", seems ok.

Fix some security vulnerabilities from dependencies

---

api/source/danger/danger_run.ts
api/source/db/json.ts
api/source/github/events/handlers/_tests/fixtures/PerilRunnerEventBootStrapExample.json
api/source/github/events/handlers/event.ts
api/source/github/events/handlers/pr.ts
api/source/github/lib/github_helpers.ts

This PR makes it possible to read settings from branches other than the default repository one. 
This is already supported by Danger using the `#<branch-name>` notation and it looks like some part of the implementation are already in Peril, but it doesn't currently work. 
Basically, these changes just make sure that the selected branch is passed down to Danger.

Fetch rules from dev branch
