.vscode/launch.json, .vscode/settings.json, package.json, source/api/__tests__/_github.test.ts, source/api/fetch.ts, source/api/github.ts, source/db/mongo.ts, source/github/events/integration_installation.ts, source/github/events/ping.ts, source/globals.ts, source/peril.ts, tslint.json, yarn.lock
Makes it so that we can ensure the typescript is best typescript.
=> Add tslint to the test output

.vscode/launch.json, README.md, dangerfile.js, source/api/github.ts, source/danger/danger_runner.ts, source/github/events/integration_installation.ts, tsconfig.json
=> Show all env vars in dangerfile

README.md, yarn.lock
Sorry @MaximeHeckel  had some pairing on another project to do, this should explain the process better. I'm still not 100% that the data storage is working 100% on my fresh setup so YMMV :D
=> Clean up README

config/default.json.example
I guess as it doesn't have the `.json` filetype, my editor didn't let me know this was really really bad JSON
=> Improve the example JSON

.gitignore, kubernetes/production.yml, kubernetes/staging.yml
I don't have any CI set up yet. Let me know if that's needed. Maybe on a fork?
=> Added configuration to deploy to Artsy kubernetes clusters

.travis.yml, README.md, source/api/_tests/_github.test.ts, source/github/lib/github_helpers.ts, source/globals.ts, source/logger.ts
=> Remove the AWS upload

CHANGELOG.md, app.json, docs/setup_for_org.md, package.json, source/github/events/github_runner.ts, source/globals.ts, source/peril.ts, source/routing/_tests/_router.test.ts, source/routing/router.ts, yarn.lock
Someone already made a node module for it, so that made it easy 👍
=> Add support for verifying GitHub webhooks via the integration secret

.vscode/settings.json, package.json, source/api/github.ts, source/db/index.ts, source/db/json.ts, yarn.lock
Just so I could start, not a biggie.
=> Update prettier, and the yarn lock

README.md, source/api/pr/dsl.ts, source/github/events/github_runner.ts, source/globals.ts, source/peril.ts, source/routing/router.ts, yarn.lock
https://peril-staging.herokuapp.com/api/v1/pr/dsl?owner=danger&repo=peril&number=104
This does work, but the files for modified/created/deleted don't seem to be showinng up yet.
=> Adds an API route for a PR's Danger DSL

package.json
=> chore(package): update danger-plugin-spellcheck to version 0.7.4

.gitignore, package.json, source/db/postgres.ts, source/github/events/github_runner.ts, source/peril-runner.ts, tsconfig.json, tslint.json, webpack.config.js, yarn.lock
Uses claudia to setup upload to AWS. The thing is, claudia doesn't support yarn - so I probably need to add that ( to ensure the lock is respected )before I can continue with claudia... Why is a shame.
=> WIP on adding AWS lambda support for the runner

package.json, source/danger/danger_runner.ts, source/github/events/createPRDSL.ts, yarn.lock
Allows Danger and Peril to post on the same PR as they both have different DangerIDs. 
/cc @damassi
=> Update Danger to support DangerID

package.json, source/danger/danger_runner.ts, yarn.lock
=> Update danger to 2.1.7

docs/setup_for_org.md
Had to update these for my new Peril server.
=> Fixes a few typos.

package.json, source/danger/_tests/_danger_runner.test.ts, source/danger/_tests/_danger_runner_paths.test.ts, source/danger/_tests/_danger_runner_peril.test.ts, source/danger/_tests/_peril_platform.test.ts, source/danger/danger_runner.ts, source/db/_tests/__snapshots__/_json.test.ts.snap, source/db/_tests/_json.test.ts, source/db/index.ts, source/db/json.ts, source/github/events/_tests/_github_runner-events.test.ts, source/github/events/_tests/_github_runner-prs.test.ts, source/github/events/_tests/_github_runner-runs.test.ts, source/github/events/_tests/_github_runner-setup.test.ts, source/github/events/_tests/_github_runner-validations.test.ts, source/github/events/create_installation.ts, source/github/events/github_runner.ts, source/globals.ts, source/peril.ts, source/routing/_tests/_router.test.ts, source/routing/_tests/_settings_updater.test.ts, source/scheduler/_tests/_runJob.test.ts, source/scheduler/_tests/_startScheduler.test.ts, source/tasks/runTask.ts, source/tasks/scheduleTask.ts, source/tasks/startTaskScheduler.ts, source/testing/installationFactory.ts, tslint.json, yarn.lock
Fixes https://github.com/danger/peril/issues/189
=> Adds support for a task scheduler from the Peril DSL

Dockerfile, Dockerfile.runner, package.json, runner/install_deps.js, tsconfig.json
I could maybe use this with hyper func.
=> Add a dockerfile for the Peril runner

docs/staging.md, package.json, source/ambient.d.ts, source/api/fetch.ts, source/danger/danger_runner.ts, source/github/events/_tests/_github_runner-events.test.ts, source/github/events/_tests/_github_runner-prs.test.ts, source/github/events/_tests/_github_runner-validations.test.ts, source/github/events/github_runner.ts, source/globals.ts, source/routing/router.ts, source/runner/index.ts, source/tasks/scheduleTask.ts, source/testing/installationFactory.ts, tsconfig.json, wallaby.js, yarn.lock
Turns on all the typescript hard mode options
=> [dev] Hard mode

docs/setup_for_org.md
=> Fix minor typo

source/peril.ts
This fixes the regenerator runtime error from #223
=> Include babel-polyfill

now.staging.json, source/api/api.ts, source/api/auth/github.ts, source/api/integration/github.ts, source/globals.ts
* Support a redirect URL in GH auth so that we can send you back to Peril
* Support sending a user to install peril at GitHub
=> Add peril.systems improvements

CHANGELOG.md, source/api/api.ts, source/api/auth/getJWTFromRequest.ts, source/api/auth/github.ts
This means SSR code and session cookies will both work
=> Support auth via cookies and basic headers

docs/updating_peril.md
I added a small document with some steps in case someone needs to update their peril instance
=> Add documentation around updating peril

docs/local_dev.md
=> Fix links in local_dev

CHANGELOG.md, source/danger/danger_runner.ts, source/github/events/github_runner.ts, source/peril.ts, source/routing/_tests/_router.test.ts, source/routing/hyper_updater.ts, source/routing/router.ts, source/routing/settings_updater.ts, source/runner/hyper-api.ts, source/runner/triggerSandboxRun.ts
Makes the logging a bit more awesome.
=> Improve logging

CHANGELOG.md, source/peril.ts, source/plugins/_tests/_installationLifeCycle.test.ts, source/plugins/_tests/_installationSettingsUpdater.test.ts, source/plugins/_tests/_validatesGithubWebhook.test.ts, source/plugins/installationLifeCycle.ts, source/plugins/installationSettingsUpdater.ts, source/plugins/validatesGithubWebhook.ts, source/routing/_tests/_router.test.ts, source/routing/router.ts
Mainly was trying to figure out how to build #255 and wanted some existing infra before tackling it.
=> Refactors some routing faffing to be 'plugins' 

package.json, yarn.lock
=> Update Danger again

README.md
This provides an explanation for what Danger JS is to the readme, in case developers land on Peril before they know what Danger is (like I did).
=> 🦉 Explain what Danger is

source/danger/_tests/_danger_runner_webhook.test.ts, source/danger/_tests/fixtures/dangerfile_empty.ts, source/danger/_tests/fixtures/dangerfile_import_complex_module.ts, source/danger/_tests/fixtures/dangerfile_import_module.ts, source/danger/_tests/fixtures/dangerfile_insecure.ts, source/danger/_tests/fixtures/dangerfile_peril_obj.ts, source/github/events/handlers/_tests/events.test.ts, source/github/events/handlers/event.ts
/cc @mxstbr 
This should fix your issues
=> Ensures that `danger.github` continues to work

CHANGELOG.md, package.json, source/ambient.d.ts, source/api/_tests/fixtureAPI.ts, source/api/api.ts, source/api/graphql/index.ts, source/api/pr/dsl.ts, source/danger/_tests/_danger_runner.test.ts, source/db/_tests/_json.test.ts, source/db/getDB.ts, source/db/json.ts, source/db/mongo.ts, source/github/events/github_runner.ts, source/index.ts, source/peril.ts, source/plugins/recordWebhooks.ts, source/plugins/utils/recordWebhookWithRequest.ts, source/routing/router.ts, source/scripts/setup-plugins.ts, tslint.json
This allows us to use Relay correctly in peril.systems
=> Adds support for the Node protocol

docs/setup_for_org.md
I added a brief note about the existence of personal servers, which I didn't see described in the docs yet.
=> Adds personal servers. Follow-up from #267.

.vscode/settings.json, CHANGELOG.md, docs/settings_repo_info.md, source/danger/_tests/_danger_run.test.ts, source/danger/danger_run.ts, source/db/_tests/_mongo.test.ts, source/db/mongo.ts, source/github/events/_tests/_github_runner-prs.test.ts, source/github/events/_tests/_github_runner-runs.test.ts, source/github/events/github_runner.ts, source/github/events/handlers/_tests/events.test.ts, yarn.lock
There we go @SD10 - adds the ability to do data comparisons in the settings json. Just uses some simple string faffing rather than anything too serious.
=> Adds the ability to do keypath based checks

CHANGELOG.md, package.json, source/api/_tests/fixtureAPI.ts, source/api/pr/dsl.ts, source/danger/_tests/_danger_runner_paths.test.ts, source/danger/_tests/_peril_platform.test.ts, source/danger/append_peril.ts, source/danger/danger_runner.ts, source/danger/peril_platform.ts, source/github/events/createPRDSL.ts, source/github/events/utils/commenting.ts, source/runner/run.ts, yarn.lock
=> Adds the checks version of danger

.vscode/settings.json, CHANGELOG.md, source/danger/_tests/_danger_runner.test.ts, source/danger/_tests/_danger_runner_paths.test.ts, source/danger/_tests/_danger_runner_webhook.test.ts, source/danger/danger_runner.ts, source/github/events/_tests/_github_runner-prs.test.ts, source/github/events/github_runner.ts, source/github/events/handlers/_tests/events.test.ts, source/github/events/handlers/event.ts, source/github/events/handlers/pr.ts, source/github/lib/github_helpers.ts, source/runner/run.ts, source/runner/triggerSandboxRun.ts, source/scheduler/_tests/_runJob.test.ts, source/scheduler/runJob.ts, source/tasks/runTask.ts
Uses the new API in Danger JS - fixes #103
=> Coalesce peril runs into a single run instead of many

.travis.yml, dangerfile.lite.ts, package.json, peril-settings-json.schema, source/db/index.ts, yarn.lock
Fixes #280 
Uses a tool that takes a TypeScript interface and makes it a JSON schema, make it easy to update.
=> Adds a JSON schema

package.json, source/danger/_tests/_danger_runner_peril.test.ts, source/danger/_tests/sandbox_stub.ts, source/danger/append_peril.ts, source/danger/peril_platform.ts, yarn.lock
Should unblock https://github.com/artsy/peril-settings/pull/58
=> Update Danger and add createUpdatedIssueWithID

source/db/mongo.ts
=> Handle repos not repo

source/github/events/create_installation.ts, source/plugins/installationLifeCycle.ts, source/routing/router.ts
Fixes https://github.com/danger/peril/issues/275  I think
=> Let the installaiton lifecycle methods eat the entire webhook for installation

source/danger/append_peril.ts, source/danger/danger_runner.ts, source/db/__mocks__/getDB.ts, source/github/events/handlers/_tests/events.test.ts
Switches to passing in the env vars over the DSL, where it should be re-accessed from the runner
=> Try fix env vars in  peril staging

docs/settings_repo_info.md, package.json, source/ambient.d.ts, source/api/api.ts, source/api/auth/getJWTFromRequest.ts, source/api/fetch.ts, source/listen.ts, source/peril.ts, source/runner/triggerSandboxRun.ts, source/tasks/_tests/_scheduleTask-prod.test.ts, yarn.lock
One way which we can avoid state in Peril is by passing things through directly, so if you're in the dashboard we open a web socket to send down useful deets
=> Add a websocket for messaging in realtime

CHANGELOG.md, package.json, source/danger/append_peril.ts
=> Adds a github utils for event runs

source/api/graphql/index.ts, source/tasks/_tests/_scheduleTask-prod.test.ts
Sibling PR: https://github.com/excitement-engineer/graphql-relay-tools/pull/7
=> Makes the connections non-null

source/api/api.ts, source/api/auth/github.ts, source/api/graphql/index.ts, source/api/graphql/mutations/_tests/_dangerfileFinished.test.ts, source/api/graphql/mutations/index.ts, source/danger/_tests/_danger_runner_paths.test.ts, source/danger/danger_runner.ts, source/github/events/_tests/_github_runner-prs.test.ts, source/github/events/github_runner.ts, source/github/events/handlers/_tests/__snapshots__/_events-create-fixture.test.ts.snap, source/github/events/handlers/_tests/__snapshots__/_pr-create-fixture.test.ts.snap, source/github/events/handlers/_tests/_events-create-fixture.test.ts, source/github/events/handlers/_tests/_events-sandbox.test.ts, source/github/events/handlers/_tests/_events.test.ts, source/github/events/handlers/_tests/_pr-create-fixture.test.ts, source/github/events/handlers/_tests/fixtures/PerilRunnerEventBootStrapExample.json, source/github/events/handlers/_tests/fixtures/PerilRunnerPRBootStrapExample.json, source/github/events/handlers/event.ts, source/github/events/handlers/pr.ts, source/runner/run.ts, source/runner/triggerSandboxRun.ts, source/tasks/runTask.ts, source/tasks/startTaskScheduler.ts
Basically expands their information so it can be presented in a UI
=> Websocket fixes

CHANGELOG.md, source/api/api.ts, source/api/graphql/mutations/index.ts, source/runner/hyper-api.ts
Wraps up the ability to send a log to a dashboard user
=> WebSocket improvements

source/danger/peril_platform.ts, source/db/__mocks__/getDB.ts, source/db/index.ts, source/db/json.ts, source/db/mongo.ts, source/scheduler/_tests/_startScheduler.test.ts, source/scheduler/startScheduler.ts
Scheduled tasks didn't work at Artsy, so... I never used them, really. This hooks them up on the staging env as well as in heroku-style versions.
=> The scheduler now works on staging

package.json
=> [package.json] allow node 8 LTS

package.json
=> Chore: make node range Heroku friendly

CHANGELOG.md, source/github/events/github_runner.ts, source/github/events/handlers/pr.ts
Fixes https://github.com/danger/peril/issues/366
=> Adds a fix for misattributed repos on a dangerfile when mixing between repos

package.json, source/api/graphql/index.ts, source/api/graphql/mutations/index.ts, source/db/mongo.ts, source/github/lib/github_helpers.ts
Migrates some of our Mutations to fit the same techniques we're using in Artsy.
=> Dashboard API work

CHANGELOG.md, now.staging.json, package.json, source/danger/_tests/_danger_run.test.ts, source/danger/danger_run.ts, source/github/events/_tests/_github_runner-runs.test.ts, source/github/events/handlers/_tests/_pr-create-fixture.test.ts, source/globals.ts, source/peril.ts, yarn.lock
=> Adds Sentry, and adds support for consolidating pull_request metadata

now.staging.json, package.json, source/api/auth/github.ts, source/api/graphql/index.ts, source/api/graphql/mutations/index.ts, source/db/mongo.ts, source/globals.ts, source/plugins/utils/recordWebhookWithRequest.ts, yarn.lock
- Adds a staging check for converting a partial installation to an installation
- Adds a root field for getting a webhook
- Ensures an installation's avatar gets saved / loaded
=> More work for the dashboard

package.json, yarn.lock
This came up [in this PR](https://github.com/artsy/peril-settings/pull/87/files#r241977347).
=> Adds googleapis dependency for downstream use

docs/local_dev.md
* Fix broken links on local_dev.md
* Add a link to the sample `docker-compose.yml`
=> Fix links on local_dev.md

api/source/api/fetch.ts, api/source/github/lib/github_helpers.ts
This is a small update to the changes I made in https://github.com/danger/peril/pull/446. It moves the logic to `fetch.ts` so that it is transparent to the Github helpers and applies tp anywhere `fetch` is called. I've also added a check that we have not exceeded the retries before throwing the error.
It more closely matches what I implemented in https://github.com/danger/danger-js/pull/898.
=> Move retry logic to fetch.ts

api/source/danger/danger_run.ts, api/source/danger/danger_runner.ts, api/source/runner/_tests/_customGitHubRequire.test.ts, api/source/runner/customGitHubRequire.ts
This adds support for relative require for PR events from github and fixes #460
=> relative require for PR events from github

api/package.json, api/yarn.lock
dependabot opened some PRs to fix some security vulnerabilities.
=> Bump handlebars and ws versions to fix security vulnerability
